# Generated by Django 4.2.11 on 2024-04-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=250, null=True, verbose_name='Пользователь')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
                ('password', models.CharField(blank=True, max_length=15, null=True, verbose_name='Пароль')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение')),
                ('tg_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя в Telegram')),
                ('message_text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('message_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время сообщения')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create_update', models.CharField(auto_created=True, null=True, verbose_name='Время создания и обновления')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Титул')),
                ('number_of_post', models.CharField(null=True, verbose_name='Номер публикации')),
                ('brand_mark', models.CharField(null=True, verbose_name='Бренды  марки')),
                ('description', models.CharField(null=True, verbose_name='Описание')),
                ('mileage', models.CharField(null=True, verbose_name='Пробег')),
                ('year', models.CharField(null=True, verbose_name='Год')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('city', models.CharField(null=True, verbose_name='Города')),
                ('photo', models.CharField(null=True, verbose_name='Фото')),
                ('parametres', models.CharField(null=True, verbose_name='Описание техническое')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofiles', to='sapp.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Авто',
                'verbose_name_plural': 'Авто',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='Администратор', max_length=500, verbose_name='Отправитель')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('message_time', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('is_reply', models.BooleanField(default=False, verbose_name='Ответ')),
                ('original_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='sapp.adminmessage', verbose_name='Исходное сообщение')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to='sapp.userprofile', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Сообщение от администратора',
                'verbose_name_plural': 'Сообщения от администратора',
            },
        ),
    ]
