# Generated by Django 4.2.11 on 2024-04-24 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0002_user_alter_adminmessage_recipient_alter_cars_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
